
name: a-quiz-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing npm
        uses: actions/setup-node@v2-beta
        with:
          version: 12

      - name: Installing yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
        
      - name: Build React App
        run: yarn build
      
      - name: Installing Surge
        run: npm install --global surge
      
      - name: Deplloying on surge
        run: surge ./build a-quiz-app.surge.sh --token ${{ secrets.SURGE_TOKEN }}
